import {
    ArrowLeft,
    Home,
    Car,
    HelpCircle,
    Shield,
    Grid,
    Locate,
    ArrowRight,
    Search,
    Wrench,
    X,
    MapPin,
    Stethoscope,
    Umbrella,
    GraduationCap,
    Ship,
    Zap,
    Briefcase,
    User,
    Plane,
    Phone,
    AlertTriangle,
    Share2,
    Navigation,
    Settings,
    Battery,
    Fuel,
    MessageCircle,
    Check,
    Clock,
    Star,
    CreditCard
} from 'lucide-react';

export const Icons = {
    ArrowLeft: ArrowLeft,
    Home: Home,
    Car: Car,
    Help: HelpCircle,
    Shield: Shield,
    Grid: Grid,
    Locate: Locate,
    ArrowRight: ArrowRight,
    Search: Search,
    Wrench: Wrench,
    Close: X,
    MapPin: MapPin,
    Medical: Stethoscope,
    Umbrella: Umbrella,
    Education: GraduationCap,
    Boat: Ship,
    Zap: Zap,
    Business: Briefcase,
    User: User,
    Plane: Plane,
    Phone: Phone,
    Alert: AlertTriangle,
    Share: Share2,
    Navigation: Navigation,
    Settings: Settings,
    Battery: Battery,
    Fuel: Fuel,
    MessageCircle: MessageCircle,
    Check: Check,
    Clock: Clock,
    Star: Star,
    CreditCard: CreditCard
};
